/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AppReservasRouteImport } from './routes/app.reservas'
import { Route as AppRecuperacionesRouteImport } from './routes/app.recuperaciones'
import { Route as AppPlanesRouteImport } from './routes/app.planes'
import { Route as AppPlanExitosoRouteImport } from './routes/app.plan-exitoso'
import { Route as AppPerfilRouteImport } from './routes/app.perfil'
import { Route as AppPagoExitosoRouteImport } from './routes/app.pago-exitoso'
import { Route as AdminPagosRouteImport } from './routes/admin.pagos'
import { Route as AdminNotificacionesRouteImport } from './routes/admin.notificaciones'
import { Route as AdminClasesRouteImport } from './routes/admin.clases'
import { Route as AdminAlumnasRouteImport } from './routes/admin.alumnas'
import { Route as ApiPublicHooksAutoCancelClassesRouteImport } from './routes/api/public/hooks/auto-cancel-classes'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AppReservasRoute = AppReservasRouteImport.update({
  id: '/reservas',
  path: '/reservas',
  getParentRoute: () => AppRoute,
} as any)
const AppRecuperacionesRoute = AppRecuperacionesRouteImport.update({
  id: '/recuperaciones',
  path: '/recuperaciones',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanesRoute = AppPlanesRouteImport.update({
  id: '/planes',
  path: '/planes',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanExitosoRoute = AppPlanExitosoRouteImport.update({
  id: '/plan-exitoso',
  path: '/plan-exitoso',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppPagoExitosoRoute = AppPagoExitosoRouteImport.update({
  id: '/pago-exitoso',
  path: '/pago-exitoso',
  getParentRoute: () => AppRoute,
} as any)
const AdminPagosRoute = AdminPagosRouteImport.update({
  id: '/pagos',
  path: '/pagos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificacionesRoute = AdminNotificacionesRouteImport.update({
  id: '/notificaciones',
  path: '/notificaciones',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClasesRoute = AdminClasesRouteImport.update({
  id: '/clases',
  path: '/clases',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlumnasRoute = AdminAlumnasRouteImport.update({
  id: '/alumnas',
  path: '/alumnas',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicHooksAutoCancelClassesRoute =
  ApiPublicHooksAutoCancelClassesRouteImport.update({
    id: '/api/public/hooks/auto-cancel-classes',
    path: '/api/public/hooks/auto-cancel-classes',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/alumnas': typeof AdminAlumnasRoute
  '/admin/clases': typeof AdminClasesRoute
  '/admin/notificaciones': typeof AdminNotificacionesRoute
  '/admin/pagos': typeof AdminPagosRoute
  '/app/pago-exitoso': typeof AppPagoExitosoRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/plan-exitoso': typeof AppPlanExitosoRoute
  '/app/planes': typeof AppPlanesRoute
  '/app/recuperaciones': typeof AppRecuperacionesRoute
  '/app/reservas': typeof AppReservasRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/api/public/hooks/auto-cancel-classes': typeof ApiPublicHooksAutoCancelClassesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/alumnas': typeof AdminAlumnasRoute
  '/admin/clases': typeof AdminClasesRoute
  '/admin/notificaciones': typeof AdminNotificacionesRoute
  '/admin/pagos': typeof AdminPagosRoute
  '/app/pago-exitoso': typeof AppPagoExitosoRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/plan-exitoso': typeof AppPlanExitosoRoute
  '/app/planes': typeof AppPlanesRoute
  '/app/recuperaciones': typeof AppRecuperacionesRoute
  '/app/reservas': typeof AppReservasRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/api/public/hooks/auto-cancel-classes': typeof ApiPublicHooksAutoCancelClassesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/alumnas': typeof AdminAlumnasRoute
  '/admin/clases': typeof AdminClasesRoute
  '/admin/notificaciones': typeof AdminNotificacionesRoute
  '/admin/pagos': typeof AdminPagosRoute
  '/app/pago-exitoso': typeof AppPagoExitosoRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/plan-exitoso': typeof AppPlanExitosoRoute
  '/app/planes': typeof AppPlanesRoute
  '/app/recuperaciones': typeof AppRecuperacionesRoute
  '/app/reservas': typeof AppReservasRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/api/public/hooks/auto-cancel-classes': typeof ApiPublicHooksAutoCancelClassesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/login'
    | '/signup'
    | '/admin/alumnas'
    | '/admin/clases'
    | '/admin/notificaciones'
    | '/admin/pagos'
    | '/app/pago-exitoso'
    | '/app/perfil'
    | '/app/plan-exitoso'
    | '/app/planes'
    | '/app/recuperaciones'
    | '/app/reservas'
    | '/admin/'
    | '/app/'
    | '/api/public/hooks/auto-cancel-classes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/admin/alumnas'
    | '/admin/clases'
    | '/admin/notificaciones'
    | '/admin/pagos'
    | '/app/pago-exitoso'
    | '/app/perfil'
    | '/app/plan-exitoso'
    | '/app/planes'
    | '/app/recuperaciones'
    | '/app/reservas'
    | '/admin'
    | '/app'
    | '/api/public/hooks/auto-cancel-classes'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/login'
    | '/signup'
    | '/admin/alumnas'
    | '/admin/clases'
    | '/admin/notificaciones'
    | '/admin/pagos'
    | '/app/pago-exitoso'
    | '/app/perfil'
    | '/app/plan-exitoso'
    | '/app/planes'
    | '/app/recuperaciones'
    | '/app/reservas'
    | '/admin/'
    | '/app/'
    | '/api/public/hooks/auto-cancel-classes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiPublicHooksAutoCancelClassesRoute: typeof ApiPublicHooksAutoCancelClassesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/reservas': {
      id: '/app/reservas'
      path: '/reservas'
      fullPath: '/app/reservas'
      preLoaderRoute: typeof AppReservasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/recuperaciones': {
      id: '/app/recuperaciones'
      path: '/recuperaciones'
      fullPath: '/app/recuperaciones'
      preLoaderRoute: typeof AppRecuperacionesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/planes': {
      id: '/app/planes'
      path: '/planes'
      fullPath: '/app/planes'
      preLoaderRoute: typeof AppPlanesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/plan-exitoso': {
      id: '/app/plan-exitoso'
      path: '/plan-exitoso'
      fullPath: '/app/plan-exitoso'
      preLoaderRoute: typeof AppPlanExitosoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pago-exitoso': {
      id: '/app/pago-exitoso'
      path: '/pago-exitoso'
      fullPath: '/app/pago-exitoso'
      preLoaderRoute: typeof AppPagoExitosoRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/pagos': {
      id: '/admin/pagos'
      path: '/pagos'
      fullPath: '/admin/pagos'
      preLoaderRoute: typeof AdminPagosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notificaciones': {
      id: '/admin/notificaciones'
      path: '/notificaciones'
      fullPath: '/admin/notificaciones'
      preLoaderRoute: typeof AdminNotificacionesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clases': {
      id: '/admin/clases'
      path: '/clases'
      fullPath: '/admin/clases'
      preLoaderRoute: typeof AdminClasesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/alumnas': {
      id: '/admin/alumnas'
      path: '/alumnas'
      fullPath: '/admin/alumnas'
      preLoaderRoute: typeof AdminAlumnasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/hooks/auto-cancel-classes': {
      id: '/api/public/hooks/auto-cancel-classes'
      path: '/api/public/hooks/auto-cancel-classes'
      fullPath: '/api/public/hooks/auto-cancel-classes'
      preLoaderRoute: typeof ApiPublicHooksAutoCancelClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAlumnasRoute: typeof AdminAlumnasRoute
  AdminClasesRoute: typeof AdminClasesRoute
  AdminNotificacionesRoute: typeof AdminNotificacionesRoute
  AdminPagosRoute: typeof AdminPagosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAlumnasRoute: AdminAlumnasRoute,
  AdminClasesRoute: AdminClasesRoute,
  AdminNotificacionesRoute: AdminNotificacionesRoute,
  AdminPagosRoute: AdminPagosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppPagoExitosoRoute: typeof AppPagoExitosoRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppPlanExitosoRoute: typeof AppPlanExitosoRoute
  AppPlanesRoute: typeof AppPlanesRoute
  AppRecuperacionesRoute: typeof AppRecuperacionesRoute
  AppReservasRoute: typeof AppReservasRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppPagoExitosoRoute: AppPagoExitosoRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppPlanExitosoRoute: AppPlanExitosoRoute,
  AppPlanesRoute: AppPlanesRoute,
  AppRecuperacionesRoute: AppRecuperacionesRoute,
  AppReservasRoute: AppReservasRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiPublicHooksAutoCancelClassesRoute: ApiPublicHooksAutoCancelClassesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
